
spring:
  application:
    name: ${SERVICE_NAME:delivery-service}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/epr_delivery}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

server:
  port: ${SERVER_PORT:8092}
  error:
    include-message: always

swagger:
  host: http://epr.thinktrash.co/api/epr

logging:
  level:
    com:
      cerclex:
        epr: ${LOG_LEVEL_APP:ERROR}
    root: ${LOG_LEVEL_ROOT:ERROR}
