
spring:
  application:
    name: ${SERVICE_NAME:authentication-service}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/epr_app}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    expiry:
      time: ${REDIS_EXPIRY:86400}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

server:
  port: ${SERVER_PORT:8555}

swagger:
  host: http://epr.thinktrash.co/api/epr

logging:
  level:
    com:
      cerclex:
        epr: ${LOG_LEVEL_APP:ERROR}
    root: ${LOG_LEVEL_ROOT:ERROR}


