spring:
  application:
    name: ${SERVICE_NAME:attachment-service}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/epr_attachment}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://naming-server:8761/eureka}

springfox:
  documentation:
    enabled: false

logging:
  level:
    com:
      cerclex:
        epr: ${LOG_LEVEL_APP:ERROR}
    root: ${LOG_LEVEL_ROOT:ERROR}



