package com.cerclex.epr.delivery.enums;

public enum AttachmentTypeEnum {
    WEIGH_BRIDGE,
    EWAY_BILL,
    SOURCE_INVOICE,
    LORRY_RECEIPT,
    VEHICLE_PHOTO,
    DELIVERY_CHALLAN,
    DROP_PROOF,
    RECYCLER_ACKNOWLEDGEMENT,
    RECYCLER_CERTIFICATE,
    CO_PROCESSING_CERTIFICATE,
    PAYMENT_PROOF,
    OTHERS
}
